### PR TITLE
[Brightroll]Adapter config update : bidfloor from 0.3 to 0.65 for BusinessInsider

### PR DESCRIPTION
**Pull request by smithaammassamveettil**
Updating adapter config bidfloor from 0.3 to 0.65 for BusinessInsider

Reviewers:
@bretg
@rpanchyk

### CODE REVIEW

**Review by rpanchyk — APPROVED** [review]

**Comment by smithaammassamveettil** [comment]
@bretg Can I get a second review/approval. When can this config change available in production?

**Review by rpanchyk — APPROVED** [review]

**Comment by rpanchyk** [comment]
Yes, if you have any changes you can push them in this PR.
This PR can be merged after your changes.

**Comment by smithaammassamveettil** [comment]
@rpanchyk I dont have any other changes. Looking for this config change to get merged and push to production. What will this change can be pushed?

**Comment by rpanchyk** [comment]
Optimistic plan to out next week.

**Comment by smithaammassamveettil** [comment]
@rpanchyk  Is this config change out now?

**Comment by rpanchyk** [comment]
No, but the plan to out this week.

**Comment by smithaammassamveettil** [comment]
Can you please update me when it is done?

**Comment by rpanchyk** [comment]
ok, i'll try but you can subscribe for project updates and see releases at https://github.com/rubicon-project/prebid-server-java/releases

**Comment by smithaammassamveettil** [comment]
@rpanchyk  Is this still not deployed to prod?

**Comment by rpanchyk** [comment]
Deployed a couple of hours ago. You can check it.

**Pull request merged**
