### PR TITLE
Brightroll bidder - Businessinsider changes and cleanup

### PR DESCRIPTION
**Pull request by smithaammassamveettil**
Description:
    -  Updated cookie sync section for Rubicon prebid server with Brightroll DSP
    -  Doing cleanup on adthrive publisher, since it is not a valid publisher for rubicon-prebid-server
    - Instead added Businessinsider publisher as initial changes , will be integrating Prebid framework support for blocked categories on top of these changes once it is ready
    - Added validation on supported vendors
    - Updated testcases for businessinsider publisher
    - Modified config for rubicon bid url/endpoints

### CODE REVIEW

**Comment by DGarbar** [comment]
Hi. Please, check https://github.com/rubicon-project/prebid-server-java/pull/649

**Comment by smithaammassamveettil** [comment]
Ok, thanks. Will make the necessary changes once the other PR merged.

**Comment by rpanchyk** [comment]
fyi, PR https://github.com/rubicon-project/prebid-server-java/pull/649 is merged to master.

**Comment by smithaammassamveettil** [comment]
Thanks @rpanchyk  for the update. Created another PR  #660 for some additional changes.

**Pull request closed without merging**
