### PR TITLE
Brightroll - cookie sync config update

### PR DESCRIPTION
**Pull request by smithaammassamveettil**
Need to update Cookie sync URL in brightroll adapter

Reviewers: @DGarbar

### CODE REVIEW

**Comment by smithaammassamveettil** [comment]
@bretg, @DGarbar  When will be the next Prebid release for this config change to happen? We would need an update in cookie sync URL for Brightroll adapter(Found out that during end to end testing today). This PR involves change in config file(brightroll.yaml) only.  Is it possible to make it available in production sooner to start integration testing?
Thanks
Smitha

**Comment by rpanchyk** [comment]
hi @smithaammassamveettil !
We plan to release in a week or two.

**Comment by smithaammassamveettil** [comment]
Hi @rpanchyk ,
Even this config change also need a complete production release? Is there anyway to make it faster than 1 week? Please let me know

Thanks
Smitha

**Comment by rpanchyk** [comment]
@smithaammassamveettil we have a plan to do this small release for you asap (1-2 days) -))

**Comment by smithaammassamveettil** [comment]
Great...Thanks alot! Please update me when it is done, so that we can start integration testing with Business Insider then.

**Comment by smithaammassamveettil** [comment]
Hi  @rpanchyk,
Is this PR released to production?
Thanks
Smitha

**Comment by bretg** [comment]
Going out today @smithaammassamveettil .

**Comment by smithaammassamveettil** [comment]
Thanks @bretg for the update

**Comment by smithaammassamveettil** [comment]
@bretg I have a question on region specific end points we have configured for Brightroll adapter. 
How do you decide (or differentiate) which end point to call when publisher calls our adapter?

**Comment by bretg** [comment]
it's region-based.

Details in email response

**Pull request merged**
